#!/usr/bin/env bash

if [[ -s "/usr/local/rvm/environments/ruby-1.9.3-p286@railsgoat" ]]
then
  source "/usr/local/rvm/environments/ruby-1.9.3-p286@railsgoat"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/environments/ruby-1.9.3-p286@railsgoat'" >&2
  exit 1
fi
