#!/usr/bin/env bash

if [[ -s "/usr/local/rvm/environments/ruby-1.9.3-p286@global" ]]
then
  source "/usr/local/rvm/environments/ruby-1.9.3-p286@global"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/environments/ruby-1.9.3-p286@global'" >&2
  exit 1
fi
