#!/usr/bin/env bash

if [[ -s "/usr/local/rvm/environments/ruby-1.9.3-p484" ]]
then
  source "/usr/local/rvm/environments/ruby-1.9.3-p484"
  exec testrb "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/environments/ruby-1.9.3-p484'" >&2
  exit 1
fi
