#!/bin/sh
set -e
# Automatically added by dh_installcatalogs
if [ "$1" = "configure" ]; then
	rm -f /etc/sgml/libcommons-validator-java.cat
	for ordcat in /usr/share/sgml/apache/jakarta/validator/catalog; do
		update-catalog --quiet --add /etc/sgml/libcommons-validator-java.cat ${ordcat}
	done
	update-catalog --quiet --add --super /etc/sgml/libcommons-validator-java.cat
fi
# End automatically added section
