#!/bin/sh -e

VERSION=8.4

# Automatically added by dh_installinit
if [ -x "/etc/init.d/postgresql-8.4" ]; then
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d postgresql-8.4 stop || exit $?
	else
		/etc/init.d/postgresql-8.4 stop || exit $?
	fi
fi
# End automatically added section


if [ "$1" = remove ]; then
    . /usr/share/postgresql-common/maintscripts-functions
    remove_version $VERSION
fi

